'''Sample configuration file generated by the "stonehenge new" command

When the command 'stonehenge build' is run in the same directory as this file,
settings from this file will be used to create a new project. Set project
parameters here.

This script will be interpreted as python, so feel free to use imports and
modules to generate values. For example, the following code would result in
a project name of "Stonehenge Example 2018" (or whatever year it is):
import datetime
year = datetime.datetime.now().year
PROJECT_NAME = "Stonehenge Example {0}".format(year)
'''
import random
import string

from django.utils.text import slugify

# REQUIRED SETTINGSs
PROJECT_NAME = ''
GITHUB_REPOSITORY = ''

# Optional Settings
PROJECT_AUTHOR = ""
PROJECT_DESCRIPTION = "Source code for the {0} project".format(PROJECT_NAME)
PROJECT_LICENSE = "ISC"
PROJECT_SLUG = slugify(PROJECT_NAME.lower()).replace("-", "_")
PROJECT_VERSION = '1.0.0'
VIRTUAL_ENVIRONMENT_NAME = 'ENV'
DJANGO_PROJECT_NAME = "app"  # Set to "PROJECT_SLUG for a standard Django layout

# Database Settings
DATABASE_PASSWORD = ''.join(
    random.choice(string.ascii_uppercase + string.digits) for _ in range(32)
)

POSTGRES_PASSWORD = 'postgrespassword'
DATABASE = {
    'local': {
        'USER': PROJECT_SLUG,
        'NAME': PROJECT_SLUG + "db",
        'PASSWORD': DATABASE_PASSWORD,
        'HOST': 'localhost',
        'POSTGRES_PASSWORD': POSTGRES_PASSWORD,
    }
}

# PIP Settings
PIP_MODULES = [
    'Django>=2.0',
]

FEATURES = [
    'public',  # Public homepage, taken from presto templates
    'user_model',  # Custom user model
]


# Wrapping all of the above into project configuration
# You probably don't need to edit anything below this line unless you're doing
# more involved customization.
PROJECT_CONFIGURATION = {
    'DATABASE': DATABASE,
    'DJANGO_PROJECT_NAME': DJANGO_PROJECT_NAME,
    'FEATURES': FEATURES,
    'GITHUB_REPOSITORY': GITHUB_REPOSITORY,
    'PIP_MODULES': PIP_MODULES,
    'PROJECT_AUTHOR': PROJECT_AUTHOR,
    'PROJECT_DESCRIPTION': PROJECT_DESCRIPTION,
    'PROJECT_LICENSE': PROJECT_LICENSE,
    'PROJECT_NAME': PROJECT_NAME,
    'PROJECT_SLUG': PROJECT_SLUG,
    'PROJECT_VERSION': PROJECT_VERSION,
    'VIRTUAL_ENVIRONMENT_NAME': VIRTUAL_ENVIRONMENT_NAME,
}
